import { HealthIntent } from "../types";

export const HEALTH_INTENTS: HealthIntent[] = [
  {
    id: "burn_care",
    title: "Thermal Burn First-Aid",
    category: "first_aid",
    keywords: ["burn", "burned", "scalding", "hot water", "hot oil", "stove burn", "jal gaya", "jalan", "jalne par", "garam tel"],
    regexPatterns: ["\\b(burn|burned|scalding|scalded)\\b", "jal\\s*gaya", "jalan"],
    urgency: "soon",
    immediateSteps: [
      "Cool the burn immediately under cool, gentle running tap water for 15-20 minutes.",
      "Remove jewelry, rings, or tight clothing around the burned area before swelling starts.",
      "Cover loosely with a clean, non-stick sterile gauze or clean plastic wrap.",
      "Take paracetamol or ibuprofen for pain relief if needed and appropriate.",
    ],
    redFlags: [
      "Burn is larger than the palm of your hand",
      "Burn is on the face, hands, groin, feet, or over major joints",
      "Skin appears charred white, brown, or leathery (3rd-degree)",
      "Chemical or electrical burn",
    ],
    doNotDo: [
      "Do NOT apply ice, ice water, or butter — this causes tissue necrosis.",
      "Do NOT pop blisters; blisters protect against infection.",
      "Do NOT apply adhesive bandages directly onto burned skin.",
    ],
    cards: [
      { type: "warn", icon: "flame", label: "Cool Water", text: "Run cool tap water for 20 mins. Never use ice." },
      { type: "tip", icon: "shield", label: "Cover Loosely", text: "Use sterile non-stick dressing or clean cling film." },
      { type: "avoid", icon: "x", label: "No Ice/Butter", text: "Folk remedies trap heat and cause severe tissue damage." },
    ],
  },
  {
    id: "cpr_adult",
    title: "Adult CPR (Hands-Only)",
    category: "emergency",
    keywords: ["cpr", "cardiopulmonary", "chest compression", "not breathing", "unresponsive", "passed out no pulse", "saans ruk gayi", "hosh me nahi"],
    regexPatterns: ["\\b(cpr|chest compression|not breathing|no pulse)\\b", "saans\\s*ruk"],
    urgency: "emergency",
    immediateSteps: [
      "CALL EMERGENCY SERVICES (112 / 911) or have someone call immediately and get an AED.",
      "Check responsiveness: Tap collarbone firmly and shout 'Are you okay?'.",
      "Place heel of one hand in the center of the chest, place other hand on top, interlocking fingers.",
      "Push hard and fast: 100-120 compressions per minute (to the beat of 'Stayin' Alive'), at least 2 inches deep.",
      "Allow chest to fully recoil between each compression.",
      "Do not stop until emergency medical help arrives or an AED is ready to analyze.",
    ],
    redFlags: [
      "Patient is unresponsive and not breathing normally (or only gasping/agonal)",
    ],
    cards: [
      { type: "warn", icon: "alert", label: "Emergency", value: "Call 112/911", text: "Call emergency services immediately before beginning CPR." },
      { type: "stat", icon: "activity", label: "Pace", value: "100-120 bpm", text: "Push hard and fast in center of the chest." },
    ],
  },
  {
    id: "choking_adult",
    title: "Choking (Heimlich Maneuver)",
    category: "emergency",
    keywords: ["choking", "choke", "cant breathe food", "object stuck throat", "heimlich", "gale me phans gaya", "dam ghut raha hai"],
    regexPatterns: ["\\b(choking|choked|heimlich)\\b", "dam\\s*ghut", "gale\\s*me\\s*phans"],
    urgency: "emergency",
    immediateSteps: [
      "Ask 'Are you choking? Can you speak or cough?'. If they can cough forcefully, encourage coughing.",
      "If they cannot speak, breathe, or make sound: Stand behind them and lean them slightly forward.",
      "Give 5 sharp back blows between shoulder blades with the heel of your hand.",
      "Give 5 abdominal thrusts: Place fist just above navel, grasp with other hand, thrust inward and upward.",
      "Alternate 5 back blows and 5 abdominal thrusts until object is expelled or person becomes unconscious.",
      "If person goes limp/unconscious, lower to floor and start CPR.",
    ],
    redFlags: [
      "Inability to speak, cyanosis (blue lips or nails), loss of consciousness",
    ],
    cards: [
      { type: "warn", icon: "alert", label: "Action", text: "Alternate 5 back blows and 5 abdominal thrusts." },
      { type: "tip", icon: "shield", label: "Position", text: "Place fist just above navel, thrust inward and upward." },
    ],
  },
  {
    id: "severe_bleeding",
    title: "Severe Bleeding & Hemorrhage Control",
    category: "emergency",
    keywords: ["bleeding heavily", "spurting blood", "deep cut bleeding", "blood loss", "arterial bleeding", "cut artery", "khoon beh raha hai", "khoon ruk nahi raha"],
    regexPatterns: ["\\b(spurting blood|heavy bleeding|bleeding heavily|arterial bleeding)\\b", "khoon\\s*beh", "khoon\\s*ruk"],
    urgency: "emergency",
    immediateSteps: [
      "Call emergency services immediately if bleeding is spurting or won't stop with pressure.",
      "Apply direct, firm pressure on the wound using a clean cloth, sterile gauze, or gloved hand.",
      "Maintain continuous pressure for at least 10-15 minutes without lifting the cloth to check.",
      "If blood soaks through, do NOT remove the first layer; add more cloths directly on top.",
      "If bleeding is from an arm or leg and direct pressure fails, apply a commercial tourniquet 2-3 inches above the wound (not over a joint).",
    ],
    redFlags: [
      "Spurting bright red blood (arterial)",
      "Bleeding continues after 15 minutes of direct pressure",
      "Signs of shock: pale skin, cold sweat, rapid breathing, confusion",
    ],
    doNotDo: [
      "Do NOT remove embedded objects (knife, glass) — pack around them to stabilize.",
    ],
    cards: [
      { type: "warn", icon: "droplet", label: "Direct Pressure", text: "Hold firm continuous pressure for 15 minutes without lifting." },
      { type: "tip", icon: "shield", label: "Do Not Remove", text: "Keep original cloth in place, layer new cloths on top." },
    ],
  },
  {
    id: "chest_pain_urgent",
    title: "Chest Pain & Suspected Heart Attack",
    category: "emergency",
    keywords: ["chest pain", "heart attack", "crushing chest", "chest tightness", "pain radiating arm jaw", "angina", "chhati me dard", "sine me dard", "seene me dard", "dil me dard"],
    regexPatterns: ["\\b(chest pain|heart attack|crushing chest|angina)\\b", "chhati\\s*me\\s*dard", "sine\\s*me\\s*dard", "seene\\s*me\\s*dard"],
    urgency: "emergency",
    immediateSteps: [
      "CALL 112 / 911 IMMEDIATELY. Do not attempt to drive yourself to the hospital.",
      "Sit or lie down in a comfortable position (semi-seated with knees bent eases cardiac workload).",
      "Loosen any tight clothing around the neck and chest.",
      "Chew and swallow one adult aspirin (300-325 mg) unless allergic or medically contraindicated.",
      "If prescribed Nitroglycerin for known heart condition, take one dose as directed.",
      "Stay calm and monitor breathing until paramedics arrive.",
    ],
    redFlags: [
      "Pressure, fullness, or squeezing pain in center of chest lasting > a few minutes",
      "Pain radiating to left arm, back, neck, jaw, or stomach",
      "Associated with shortness of breath, cold sweat, nausea, lightheadedness",
    ],
    cards: [
      { type: "warn", icon: "heart", label: "Emergency", value: "Call 112/911", text: "Every minute counts for cardiac ischemia." },
      { type: "med", icon: "pill", label: "Aspirin 300mg", text: "Chew non-enteric coated aspirin if not allergic." },
    ],
  },
  {
    id: "stroke_fast",
    title: "Stroke Signs (FAST Protocol)",
    category: "emergency",
    keywords: ["stroke", "face drooping", "arm weakness", "slurred speech", "paralysis one side", "brain stroke", "lakwa", "muh tedha", "bolne me dikkat"],
    regexPatterns: ["\\b(stroke|fast protocol|face drooping|slurred speech)\\b", "lakwa"],
    urgency: "emergency",
    immediateSteps: [
      "Use F.A.S.T. to identify stroke immediately:",
      "F - Face: Ask the person to smile. Does one side of the face droop?",
      "A - Arms: Ask person to raise both arms. Does one arm drift downward?",
      "S - Speech: Ask person to repeat a simple phrase. Is speech slurred or strange?",
      "T - Time: If ANY of these signs are present, CALL EMERGENCY (112/911) IMMEDIATELY.",
      "Note the exact time symptoms started — clot-busting treatments require rapid administration.",
      "Do NOT give anything to eat, drink, or medication (no aspirin until CT confirms ischemic vs hemorrhagic).",
    ],
    redFlags: [
      "Sudden numbness or weakness of face, arm, or leg, especially on one side of the body",
      "Sudden confusion, trouble speaking, or difficulty understanding speech",
      "Sudden trouble seeing in one or both eyes, loss of balance, or thunderclap headache",
    ],
    cards: [
      { type: "warn", icon: "activity", label: "FAST Protocol", text: "Face drooping, Arm drift, Slurred speech = Immediate Emergency." },
      { type: "avoid", icon: "x", label: "No Food/Aspirin", text: "Do not give aspirin until hospital CT rules out bleed." },
    ],
  },
  {
    id: "anaphylaxis",
    title: "Severe Allergic Reaction (Anaphylaxis)",
    category: "emergency",
    keywords: ["anaphylaxis", "severe allergy", "throat swelling", "epipen", "swollen tongue", "cant breathe allergy", "gala sooj gaya", "allergic reaction"],
    regexPatterns: ["\\b(anaphylaxis|throat swelling|epipen|swelling tongue)\\b", "gala\\s*sooj"],
    urgency: "emergency",
    immediateSteps: [
      "Administer Epinephrine Auto-Injector (EpiPen) into the outer mid-thigh immediately if available.",
      "Call emergency services (112/911) right after injecting.",
      "Keep person lying flat on back with feet elevated. If breathing is difficult, allow them to sit up.",
      "A second dose of epinephrine can be given after 5-15 minutes if symptoms do not improve.",
    ],
    redFlags: [
      "Difficulty breathing, wheezing, or stridor",
      "Swelling of tongue, throat, or lips",
      "Dizziness, feeling faint, or collapse",
    ],
    cards: [
      { type: "warn", icon: "alert", label: "EpiPen First", text: "Inject outer thigh immediately. Hold for 3 seconds." },
      { type: "tip", icon: "shield", label: "Lie Flat", text: "Keep legs elevated unless severe breathing difficulty." },
    ],
  },
  {
    id: "asthma_attack",
    title: "Acute Asthma Attack & Inhaler Protocol",
    category: "emergency",
    keywords: ["asthma attack", "wheezing badly", "inhaler not working", "cant breathe asthma", "salbutamol dose", "dama", "saans phoolna", "saans lene me takleef"],
    regexPatterns: ["\\b(asthma attack|wheezing badly|asthma flare)\\b", "saans\\s*phool", "saans\\s*lene\\s*me\\s*takleef"],
    urgency: "soon",
    immediateSteps: [
      "Sit upright comfortably — do not lie down.",
      "Take 1 puff of rescue inhaler (Salbutamol/Albuterol, usually blue) every 30-60 seconds, up to 10 puffs.",
      "Use a spacer device if available for optimal drug delivery.",
      "If symptoms do not improve after 10 puffs, call emergency services immediately.",
    ],
    redFlags: [
      "Too breathless to speak in full sentences",
      "Blue or pale tinge to lips, gums, or nail beds",
      "Chest and neck sucking in during breaths (retractions)",
    ],
    cards: [
      { type: "med", icon: "pill", label: "Rescue Inhaler", text: "1 puff every 30-60s up to 10 puffs with spacer." },
      { type: "warn", icon: "alert", label: "Sit Upright", text: "Never lie down during an asthma exacerbation." },
    ],
  },
  {
    id: "infant_fever",
    title: "Fever in Infants Under 3 Months",
    category: "pediatric",
    keywords: ["baby fever", "infant fever", "newborn fever", "fever 2 month old", "fever under 3 months", "bachhe ko bukhar", "chote baby ko bukhar", "baby bukhar"],
    regexPatterns: ["\\b(baby fever|infant fever|newborn fever|fever.*month)\\b", "bachhe\\s*ko\\s*bukhar", "baby.*bukhar"],
    urgency: "emergency",
    immediateSteps: [
      "Any rectal or axillary temperature of 100.4°F (38.0°C) or higher in an infant under 3 months requires IMMEDIATE SAME-DAY EMERGENCY MEDICAL EVALUATION.",
      "Do NOT give over-the-counter fever reducers without direct pediatrician guidance.",
      "Keep baby in a single layer of lightweight clothing.",
      "Offer frequent breast milk or formula to maintain hydration.",
    ],
    redFlags: [
      "Lethargy, difficult to wake, or weak high-pitched cry",
      "Refusing to feed, fewer wet diapers (under 4 in 24 hours)",
      "Bulging soft spot (fontanelle) or petechial purple rash",
    ],
    cards: [
      { type: "warn", icon: "thermometer", label: "Threshold", value: "≥ 100.4°F (38°C)", text: "Immediate ER evaluation required for <3 month olds." },
      { type: "avoid", icon: "x", label: "No Meds First", text: "Do not give OTC antipyretics without doctor assessment." },
    ],
  },
  {
    id: "seizure_firstaid",
    title: "Seizure & Convulsion Safety",
    category: "emergency",
    keywords: ["seizure", "convulsion", "fits", "shaking uncontrollably", "epileptic seizure", "mirgi", "daura padna", "jhatke aana"],
    regexPatterns: ["\\b(seizure|convulsion|epilepsy fit)\\b", "mirgi", "daura"],
    urgency: "emergency",
    immediateSteps: [
      "Clear the surrounding area of hard, sharp, or dangerous objects.",
      "Ease the person onto the floor and place something soft (folded jacket) under their head.",
      "Turn person gently onto their side (recovery position) to keep airway clear.",
      "Time the seizure. If it lasts longer than 5 minutes, call 112/911 immediately.",
      "Stay with the person until they are fully awake and alert.",
    ],
    redFlags: [
      "Seizure lasts > 5 minutes, or a second seizure starts right away",
      "Person is pregnant, injured, or in water",
      "Difficulty breathing or waking up after the seizure stops",
    ],
    doNotDo: [
      "Do NOT hold the person down or restrain their movements.",
      "Do NOT put anything in their mouth (they cannot swallow their tongue).",
    ],
    cards: [
      { type: "tip", icon: "shield", label: "Protect Head", text: "Place folded cloth under head and clear hard objects." },
      { type: "avoid", icon: "x", label: "Nothing in Mouth", text: "Never insert spoons, cloths, or fingers into mouth." },
    ],
  },
  {
    id: "diabetic_hypo",
    title: "Diabetic Hypoglycemia (Low Blood Sugar)",
    category: "emergency",
    keywords: ["low sugar", "hypoglycemia", "diabetic shaking", "sugar drop", "insulin shock", "sugar kam ho gaya", "sugar gir gaya"],
    regexPatterns: ["\\b(hypoglycemia|low blood sugar|sugar drop|low sugar)\\b", "sugar\\s*kam"],
    urgency: "soon",
    immediateSteps: [
      "Follow the 15-15 Rule if person is conscious and able to swallow:",
      "Consume 15 grams of fast-acting carbohydrate: 4 glucose tablets, half cup (120ml) fruit juice or regular soda, or 3-4 teaspoons sugar/honey in water.",
      "Wait 15 minutes and re-check blood glucose level.",
      "If blood sugar remains below 70 mg/dL (3.9 mmol/L), repeat with another 15g fast carbohydrate.",
      "Once stabilized, eat a small snack with complex carbs and protein (crackers with cheese, toast).",
    ],
    redFlags: [
      "Person is unconscious, seizing, or unable to swallow safely — call 112/911 and administer glucagon if trained.",
    ],
    cards: [
      { type: "stat", icon: "activity", label: "15-15 Rule", value: "15g Carbs", text: "Juice, glucose tablets, or 3 tsp sugar in water." },
      { type: "tip", icon: "check", label: "Recheck", value: "15 Mins", text: "Test glucose level 15 minutes after consuming carbs." },
    ],
  },
  {
    id: "heatstroke",
    title: "Heatstroke & Severe Heat Exhaustion",
    category: "emergency",
    keywords: ["heat stroke", "heatstroke", "overheating sun", "hot red dry skin", "passed out heat", "loo lagna", "garmi se behosh"],
    regexPatterns: ["\\b(heat stroke|heatstroke)\\b", "loo\\s*lag"],
    urgency: "emergency",
    immediateSteps: [
      "Call emergency services immediately — heatstroke is a life-threatening medical emergency.",
      "Move person to a cool, shaded, or air-conditioned area immediately.",
      "Cool the body rapidly: Apply cool wet towels, mist with water, and fan aggressively.",
      "Place ice packs or cold wet cloths on neck, armpits, and groin where major blood vessels pass.",
      "If conscious and alert, offer sips of cool water or electrolyte drink.",
    ],
    redFlags: [
      "Body temperature > 103°F (39.4°C)",
      "Hot, red, dry skin (or heavy sweating that suddenly stops)",
      "Confusion, slurred speech, delirium, seizures, or loss of consciousness",
    ],
    cards: [
      { type: "warn", icon: "flame", label: "Rapid Cooling", text: "Cold compresses on neck, armpits, groin and fan vigorously." },
      { type: "stat", icon: "thermometer", label: "Temp Warning", value: "> 103°F", text: "True heatstroke requires emergency hospital hydration." },
    ],
  },
  {
    id: "poisoning_ingestion",
    title: "Accidental Poisoning & Toxic Ingestion",
    category: "emergency",
    keywords: ["drank bleach", "swallowed poison", "swallowed pills", "toxic ingestion", "child drank cleaner", "overdose", "zeher", "dawa overdose"],
    regexPatterns: ["\\b(swallowed poison|drank bleach|toxic ingestion|overdose)\\b", "zeher"],
    urgency: "emergency",
    immediateSteps: [
      "Call National Poison Center or Emergency (112/911) immediately.",
      "Identify the substance: Have the exact bottle, package, or label ready to describe.",
      "Estimate the amount ingested and the time it occurred.",
      "Remove any residual chemicals from person's mouth or skin.",
    ],
    doNotDo: [
      "Do NOT induce vomiting unless explicitly instructed by poison control (causes secondary chemical burns).",
      "Do NOT give milk, raw eggs, or salt water.",
    ],
    cards: [
      { type: "warn", icon: "alert", label: "Keep Bottle", text: "Save the product container for emergency staff." },
      { type: "avoid", icon: "x", label: "Do Not Vomit", text: "Inducing vomiting burns the esophagus twice." },
    ],
  },
  {
    id: "snake_bite",
    title: "Snake Bite First-Aid",
    category: "emergency",
    keywords: ["snake bite", "bitten by snake", "viper bite", "cobra bite", "saanp ne kaat liya", "saamp kaatna"],
    regexPatterns: ["\\b(snake bite|snakebite|bitten by snake)\\b", "saanp", "saamp"],
    urgency: "emergency",
    immediateSteps: [
      "Call emergency services immediately and transport to hospital equipped with anti-snake venom (ASV).",
      "Keep the victim calm and still — movement spreads venom faster through the lymphatic system.",
      "Immobilize the bitten limb with a splint at or slightly below heart level.",
      "Remove tight rings, watches, or restrictive clothing before swelling begins.",
    ],
    doNotDo: [
      "Do NOT cut the wound, suck out venom, or apply ice.",
      "Do NOT apply a tight arterial tourniquet.",
    ],
    cards: [
      { type: "warn", icon: "shield", label: "Immobilize", text: "Keep limb still below heart level; avoid walking." },
      { type: "avoid", icon: "x", label: "No Sucking/Cut", text: "Never cut wound or suck venom; damages tissue." },
    ],
  },
  {
    id: "nosebleed_epistaxis",
    title: "Nosebleed (Epistaxis) Management",
    category: "first_aid",
    keywords: ["nosebleed", "bloody nose", "bleeding from nose", "epistaxis", "nakseer", "naak se khoon"],
    regexPatterns: ["\\b(nosebleed|bloody nose|bleeding from nose)\\b", "nakseer", "naak\\s*se\\s*khoon"],
    urgency: "self_care",
    immediateSteps: [
      "Sit upright and lean slightly forward (do NOT tilt head back — blood drains into stomach).",
      "Pinch the soft part of the nose (just below the nasal bone) firmly with thumb and index finger.",
      "Breathe through mouth and maintain continuous pinch for a full 10-15 minutes without releasing.",
      "Apply an ice pack or cold compress across bridge of nose and cheeks.",
    ],
    redFlags: [
      "Bleeding continues after 20 minutes of firm direct pressure",
      "Follows significant head trauma",
      "Associated with dizziness or large volume blood loss",
    ],
    cards: [
      { type: "tip", icon: "check", label: "Lean Forward", text: "Never tilt head back; prevents blood swallowing and choking." },
      { type: "stat", icon: "activity", label: "Pinch Duration", value: "10-15 Mins", text: "Pinch soft part of nose continuously." },
    ],
  },
  {
    id: "sprain_rice",
    title: "Sprained Ankle / Muscle Strain (R.I.C.E.)",
    category: "first_aid",
    keywords: ["twisted ankle", "sprained ankle", "sprain", "strained muscle", "swollen ankle", "moch aa gayi", "pair mud gaya", "moch"],
    regexPatterns: ["\\b(sprained|sprain|twisted ankle|strained muscle)\\b", "moch"],
    urgency: "self_care",
    immediateSteps: [
      "Follow R.I.C.E. protocol for the first 48-72 hours:",
      "Rest: Protect injured joint; avoid putting weight on it.",
      "Ice: Apply cold pack wrapped in thin towel for 15-20 minutes every 2-3 hours.",
      "Compression: Wrap with an elastic bandage (snug, but not cutting off circulation).",
      "Elevation: Elevate the injured limb above heart level whenever resting to minimize swelling.",
    ],
    redFlags: [
      "Inability to bear any weight (4 steps)",
      "Severe bony tenderness or deformity (possible fracture, requires X-ray)",
      "Numbness, tingling, or cold toes/fingers",
    ],
    cards: [
      { type: "tip", icon: "shield", label: "R.I.C.E.", text: "Rest, Ice (20m), Compression wrap, Elevation above heart." },
      { type: "remedy", icon: "leaf", label: "Pain Relief", text: "Paracetamol or ibuprofen if stomach allows." },
    ],
  },
  {
    id: "panic_attack",
    title: "Panic Attack & Hyperventilation",
    category: "general_health",
    keywords: ["panic attack", "anxiety attack", "hyperventilating", "racing heart anxiety", "cant catch breath anxiety", "ghabrahat", "bechaini"],
    regexPatterns: ["\\b(panic attack|hyperventilating|anxiety attack)\\b", "ghabrahat", "bechaini"],
    urgency: "self_care",
    immediateSteps: [
      "Recognize that panic attacks, while frightening, are temporary and not physically dangerous.",
      "Practice 4-7-8 Box Breathing: Inhale through nose for 4 seconds, hold for 7 seconds, exhale slowly through mouth for 8 seconds.",
      "Grounding technique (5-4-3-2-1): Name 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste.",
      "Loosen tight clothing and sit in a comfortable, quiet space.",
    ],
    redFlags: [
      "Chest pain with radiation to arm/jaw or shortness of breath not easing with breathing control (must rule out cardiac event)",
    ],
    cards: [
      { type: "tip", icon: "activity", label: "4-7-8 Breathing", text: "Inhale 4s, hold 7s, slow exhale 8s to calm vagus nerve." },
      { type: "stat", icon: "heart", label: "Grounding", value: "5-4-3-2-1", text: "Engage your physical senses to anchor focus." },
    ],
  },
];
