-- Medi Bud: Initial Relational PostgreSQL Schema for Supabase
-- Target: Supabase Postgres with Row Level Security (RLS) enabled on all tables

-- 1. Profiles Table (1:N under auth.users)
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  account_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Primary',
  relationship text not null default 'self' check (relationship in ('self', 'parent', 'child', 'spouse', 'other')),
  age integer not null check (age >= 0 and age <= 130),
  gender text not null,
  height_cm real not null,
  weight_kg real not null,
  health_issues text not null default '',
  medications text not null default '',
  allergies text not null default '',
  updated_at bigint not null
);

-- 2. Conversations Table (scoped to profile)
create table if not exists public.conversations (
  id text primary key,
  account_id uuid not null references auth.users(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  title text not null,
  created_at bigint not null,
  updated_at bigint not null
);

-- 3. Chat Messages Table
create table if not exists public.chat_messages (
  id text primary key,
  conversation_id text not null references public.conversations(id) on delete cascade,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  cards_json text,
  interactive_json text,
  image_uri text,
  source text not null default 'cloud',
  is_offline smallint not null default 0,
  created_at bigint not null
);

-- 4. Medication Reminders Table
create table if not exists public.reminders (
  id bigint generated by default as identity primary key,
  account_id uuid not null references auth.users(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  name text not null,
  dosage text not null default '',
  frequency text not null default 'daily',
  time text not null,
  active smallint not null default 1,
  created_at bigint not null
);

-- 5. Symptom Evaluations Table
create table if not exists public.symptom_evaluations (
  id text primary key,
  account_id uuid not null references auth.users(id) on delete cascade,
  profile_id bigint not null references public.profiles(id) on delete cascade,
  symptoms_json text not null,
  urgency text not null,
  advice text not null,
  red_flags_detected smallint not null default 0,
  created_at bigint not null
);

-- Indexes for performance
create index if not exists idx_profiles_account on public.profiles(account_id);
create index if not exists idx_conversations_account on public.conversations(account_id);
create index if not exists idx_conversations_profile on public.conversations(profile_id);
create index if not exists idx_chat_messages_conv on public.chat_messages(conversation_id);
create index if not exists idx_reminders_account on public.reminders(account_id);
create index if not exists idx_reminders_profile on public.reminders(profile_id);
create index if not exists idx_symptom_evals_account on public.symptom_evaluations(account_id);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.chat_messages enable row level security;
alter table public.reminders enable row level security;
alter table public.symptom_evaluations enable row level security;

-- RLS Policies: Authenticated users manage only their own account's records
create policy "Users can manage own profiles"
  on public.profiles for all
  using (auth.uid() = account_id)
  with check (auth.uid() = account_id);

create policy "Users can manage own conversations"
  on public.conversations for all
  using (auth.uid() = account_id)
  with check (auth.uid() = account_id);

create policy "Users can manage messages in own conversations"
  on public.chat_messages for all
  using (
    exists (
      select 1 from public.conversations c
      where c.id = chat_messages.conversation_id
      and c.account_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.conversations c
      where c.id = chat_messages.conversation_id
      and c.account_id = auth.uid()
    )
  );

create policy "Users can manage own reminders"
  on public.reminders for all
  using (auth.uid() = account_id)
  with check (auth.uid() = account_id);

create policy "Users can manage own evaluations"
  on public.symptom_evaluations for all
  using (auth.uid() = account_id)
  with check (auth.uid() = account_id);
