import { MealItem } from "./types";

export const MEAL_CATALOG: MealItem[] = [
  // --- BREAKFAST ---
  {
    id: "bf_oats_chilla",
    name: "Vegetable Oats & Besan Chilla",
    nameHi: "सब्जियों वाला ओट्स और बेसन चीला",
    portion: "2 Chillas + 2 tbsp Mint Chutney",
    portionHi: "2 चीले + 2 चम्मच पुदीना चटनी",
    mealType: "breakfast",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg"],
    cuisines: ["simple_home", "north_indian", "high_protein"],
    calories: 320,
    proteinG: 14,
    carbsG: 44,
    fatG: 9,
    fiberG: 7,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: [],
    healthTags: ["Low GI", "High Fiber", "Heart Safe"],
    prepTip: "Whisk rolled oats flour and besan with grated bottle gourd and mild cumin.",
  },
  {
    id: "bf_ragi_dosa",
    name: "Ragi & Urad Dal Dosa with Veggie Sambar",
    nameHi: "रागी डोसा और सांभर",
    portion: "2 Dosas + 1 cup Drumstick & Bottle Gourd Sambar",
    portionHi: "2 डोसे + 1 कटोरी सांभर",
    mealType: "breakfast",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["south_indian", "simple_home"],
    calories: 310,
    proteinG: 11,
    carbsG: 52,
    fatG: 6,
    fiberG: 9,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: [],
    healthTags: ["Gluten Free", "Calcium Rich", "Low GI"],
    prepTip: "Ferment ragi flour with urad batter; use minimal oil on an iron tawa.",
  },
  {
    id: "bf_egg_spinach_toast",
    name: "Boiled Eggs & Sauteed Spinach on Whole Grain Toast",
    nameHi: "उबले अंडे और पालक टोस्ट",
    portion: "2 Eggs (1 whole + 1 white) + 2 slices Multi-grain Toast + Spinach",
    portionHi: "2 अंडे + 2 मल्टीग्रेन ब्रेड + उबला पालक",
    mealType: "breakfast",
    dietTypes: ["eggetarian", "non_veg"],
    cuisines: ["simple_home", "high_protein"],
    calories: 340,
    proteinG: 22,
    carbsG: 32,
    fatG: 12,
    fiberG: 5,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: ["egg", "gluten"],
    healthTags: ["High Protein", "Low GI"],
    prepTip: "Boil eggs firmly and lightly saute spinach with crushed black pepper.",
  },
  {
    id: "bf_jain_poha",
    name: "Steamed Vegetable Poha (No Onion/Garlic)",
    nameHi: "स्वादिष्ट पोहा (बिना प्याज/लहसुन)",
    portion: "1.5 cups Poha with Green Peas & Roasted Peanuts",
    portionHi: "1.5 कटोरी पोहा (मटर व मूंगफली के साथ)",
    mealType: "breakfast",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["simple_home", "north_indian"],
    calories: 290,
    proteinG: 8,
    carbsG: 48,
    fatG: 8,
    fiberG: 5,
    sodiumLevel: "low",
    giLevel: "medium",
    allergens: ["peanut"],
    healthTags: ["Easy Digestion", "Iron Rich"],
    prepTip: "Rinse thick poha and temper with mustard seeds, curry leaves, and turmeric.",
  },
  {
    id: "bf_paneer_bhurji_wrap",
    name: "Low-Fat Paneer Bhurji with 1 Phulka",
    nameHi: "पनीर भुर्जी और 1 फुल्का",
    portion: "100g Paneer Bhurji + 1 Whole Wheat Phulka",
    portionHi: "100 ग्राम पनीर भुर्जी + 1 गेहूं की रोटी",
    mealType: "breakfast",
    dietTypes: ["veg", "eggetarian", "non_veg"],
    cuisines: ["north_indian", "high_protein"],
    calories: 350,
    proteinG: 21,
    carbsG: 28,
    fatG: 15,
    fiberG: 4,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: ["dairy", "gluten"],
    healthTags: ["High Protein", "Low GI"],
    prepTip: "Use skimmed milk paneer and saute with diced capsicum and tomatoes.",
  },

  // --- MORNING SNACK ---
  {
    id: "ms_soaked_nuts_apple",
    name: "Crisp Apple Slices & Soaked Almonds",
    nameHi: "सेब के टुकड़े और भीगे बादाम",
    portion: "1 Medium Apple + 6 Soaked Pealed Almonds + 2 Walnuts",
    portionHi: "1 मध्यम सेब + 6 भीगे बादाम + 2 अखरोट",
    mealType: "morning_snack",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["simple_home", "north_indian", "south_indian", "high_protein"],
    calories: 160,
    proteinG: 4,
    carbsG: 22,
    fatG: 8,
    fiberG: 5,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: ["nut"],
    healthTags: ["Heart Safe", "Brain Health", "Antioxidants"],
    prepTip: "Soak nuts overnight to neutralize phytic acid and optimize nutrient absorption.",
  },
  {
    id: "ms_sprouts_salad",
    name: "Steamed Moong Sprouts Salad",
    nameHi: "उबले मूंग स्प्राउट्स सलाद",
    portion: "1 Cup Sprouts + Lemon Juice + Diced Cucumber & Tomato",
    portionHi: "1 कटोरी अंकुरित मूंग + खीरा, टमाटर और नींबू रस",
    mealType: "morning_snack",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["simple_home", "high_protein"],
    calories: 140,
    proteinG: 10,
    carbsG: 22,
    fatG: 1,
    fiberG: 6,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: [],
    healthTags: ["Low GI", "High Fiber", "Zero Fat"],
    prepTip: "Steam sprouts for 3 minutes for easy digestion without bloating.",
  },

  // --- LUNCH ---
  {
    id: "lu_dal_phulka_sabzi",
    name: "Yellow Moong Dal, Lauki Sabzi & 2 Phulkas",
    nameHi: "मूंग दाल, लौकी सब्जी और 2 पतली रोटियां",
    portion: "1 bowl Dal + 1 bowl Lauki Sabzi + 2 Phulkas + Cucumber Salad",
    portionHi: "1 कटोरी दाल + 1 कटोरी लौकी + 2 रोटियां + खीरा सलाद",
    mealType: "lunch",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["simple_home", "north_indian"],
    calories: 460,
    proteinG: 18,
    carbsG: 72,
    fatG: 9,
    fiberG: 12,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: ["gluten"],
    healthTags: ["DASH Friendly", "High Fiber", "Gut Friendly"],
    prepTip: "Cook dal with a pinch of hing and jeera; avoid heavy tadka.",
  },
  {
    id: "lu_sambar_brown_rice",
    name: "South Indian Sambar, Beetroot Poriyal & Brown Rice",
    nameHi: "सांभर, चुकंदर पोरियाल और ब्राउन राइस",
    portion: "1 cup Cooked Brown Rice + 1.5 cups Veggie Sambar + 1 cup Poriyal",
    portionHi: "1 कटोरी ब्राउन राइस + सांभर + चुकंदर सब्जी",
    mealType: "lunch",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["south_indian", "simple_home"],
    calories: 450,
    proteinG: 16,
    carbsG: 78,
    fatG: 7,
    fiberG: 14,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: [],
    healthTags: ["Gluten Free", "Heart Safe", "High Fiber"],
    prepTip: "Use brown unpolished rice and pack the sambar with pumpkin, drumsticks and methi.",
  },
  {
    id: "lu_grilled_chicken_bowl",
    name: "Herb Grilled Chicken with Quinoa & Steamed Greens",
    nameHi: "हर्ब ग्रिल्ड चिकन और क्विनोआ बाउल",
    portion: "150g Chicken Breast + 1 cup Cooked Quinoa + Steamed Broccoli/Beans",
    portionHi: "150 ग्राम चिकन + 1 कटोरी क्विनोआ + उबली सब्जियां",
    mealType: "lunch",
    dietTypes: ["non_veg"],
    cuisines: ["high_protein", "simple_home"],
    calories: 480,
    proteinG: 42,
    carbsG: 46,
    fatG: 11,
    fiberG: 8,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: [],
    healthTags: ["High Protein", "Gluten Free", "Low GI"],
    prepTip: "Marinate chicken in lemon juice, garlic, turmeric, and black pepper; grill without charring.",
  },
  {
    id: "lu_tofu_veggie_stirfry",
    name: "Tofu & Mixed Veggie Stir-fry with Brown Rice",
    nameHi: "टोफू व हरी सब्जियों का स्टिर-फ्राई और ब्राउन राइस",
    portion: "120g Tofu + 1.5 cups Sauteed Bell Peppers/Carrots/Beans + 1 cup Rice",
    portionHi: "120 ग्राम टोफू + भुनी सब्जियां + 1 कटोरी चावल",
    mealType: "lunch",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["high_protein", "simple_home"],
    calories: 440,
    proteinG: 24,
    carbsG: 58,
    fatG: 12,
    fiberG: 9,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: ["soy"],
    healthTags: ["Dairy Free", "Plant Protein", "Low GI"],
    prepTip: "Press tofu to release water, dice and pan-sear with sesame seeds and ginger.",
  },

  // --- EVENING SNACK ---
  {
    id: "es_roasted_makhana",
    name: "Roasted Makhana (Fox Nuts) with Green Tea",
    nameHi: "भुना मखाना और ग्रीन टी",
    portion: "1 Bowl Roasted Makhana (light turmeric & salt) + 1 Cup Green Tea",
    portionHi: "1 कटोरी भुना मखाना + 1 कप ग्रीन टी",
    mealType: "evening_snack",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["simple_home", "north_indian", "south_indian", "high_protein"],
    calories: 120,
    proteinG: 4,
    carbsG: 22,
    fatG: 2,
    fiberG: 4,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: [],
    healthTags: ["Gluten Free", "Low Calorie", "Kidney Safe"],
    prepTip: "Dry roast makhanas on low flame with 1/2 tsp ghee and a dash of rock salt.",
  },
  {
    id: "es_roasted_chana",
    name: "Roasted Bengal Gram (Bhuna Chana)",
    nameHi: "भुना चना और नींबू पानी",
    portion: "30g Roasted Chana + 1 Glass Lemon Chia Water (No Sugar)",
    portionHi: "30 ग्राम भुना चना + नींबू पानी",
    mealType: "evening_snack",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["simple_home", "high_protein"],
    calories: 130,
    proteinG: 7,
    carbsG: 19,
    fatG: 3,
    fiberG: 5,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: [],
    healthTags: ["High Fiber", "Satiety Booster", "Diabetes Safe"],
    prepTip: "Rich in slow-burning complex carbs and plant protein to avoid evening sugar cravings.",
  },

  // --- DINNER ---
  {
    id: "di_moong_khichdi",
    name: "Moong Dal & Vegetable Khichdi with Dahi",
    nameHi: "मूंग दाल खिचड़ी और ताजा दही",
    portion: "1.5 cups Soft Khichdi + 1/2 cup Low-Fat Curd",
    portionHi: "1.5 कटोरी नरम खिचड़ी + आधी कटोरी दही",
    mealType: "dinner",
    dietTypes: ["veg", "eggetarian", "non_veg", "jain"],
    cuisines: ["simple_home", "north_indian"],
    calories: 390,
    proteinG: 16,
    carbsG: 62,
    fatG: 7,
    fiberG: 8,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: ["dairy"],
    healthTags: ["Light on Stomach", "Anti-Reflux", "Gut Probiotic"],
    prepTip: "Prepare with equal parts moong dal and rice, spiced gently with jeera and turmeric.",
  },
  {
    id: "di_methi_phulka_paneer",
    name: "Methi Phulkas with Sauteed Paneer & Bhindi",
    nameHi: "मेथी की रोटी, पनीर और भिंडी की सब्जी",
    portion: "2 Methi Phulkas + 80g Paneer + 1 bowl Bhindi",
    portionHi: "2 मेथी रोटी + 80 ग्राम पनीर + भिंडी सब्जी",
    mealType: "dinner",
    dietTypes: ["veg", "eggetarian", "non_veg"],
    cuisines: ["north_indian", "high_protein"],
    calories: 420,
    proteinG: 20,
    carbsG: 48,
    fatG: 15,
    fiberG: 10,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: ["dairy", "gluten"],
    healthTags: ["High Fiber", "Low GI", "Muscle Recovery"],
    prepTip: "Knead fresh fenugreek (methi) leaves into whole wheat atta to lower the glycemic response.",
  },
  {
    id: "di_fish_curry_idli",
    name: "Steamed Idlis with Light Fish Curry",
    nameHi: "इडली और हल्की मछली करी",
    portion: "3 Soft Idlis + 120g Steamed Fish in Light Tomato-Kari Gravy",
    portionHi: "3 इडली + 120 ग्राम मछली करी",
    mealType: "dinner",
    dietTypes: ["non_veg"],
    cuisines: ["south_indian", "high_protein"],
    calories: 410,
    proteinG: 28,
    carbsG: 50,
    fatG: 8,
    fiberG: 4,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: ["fish"],
    healthTags: ["Omega 3", "Heart Safe", "Gluten Free"],
    prepTip: "Steam fish in a light kokum or tomato broth; avoid heavy coconut cream.",
  },
  {
    id: "di_jowar_roti_palak",
    name: "Jowar Roti with Palak & Dal",
    nameHi: "ज्वार की रोटी और पालक दाल",
    portion: "2 Jowar Rotis + 1.5 cups Palak Dal + Radish slices",
    portionHi: "2 ज्वार रोटी + 1.5 कटोरी पालक दाल",
    mealType: "dinner",
    dietTypes: ["veg", "vegan", "eggetarian", "non_veg", "jain"],
    cuisines: ["simple_home", "north_indian", "south_indian"],
    calories: 380,
    proteinG: 17,
    carbsG: 64,
    fatG: 6,
    fiberG: 14,
    sodiumLevel: "low",
    giLevel: "low",
    allergens: [],
    healthTags: ["Gluten Free", "Iron Rich", "Low GI"],
    prepTip: "Knead warm water into jowar flour to roll soft, nutrient-dense rotis.",
  },
];
